spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mini_bank
    username: kodilla_user
    password: kodilla_password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      database: mysql
  application:
  name: transfers-realization-com.kodilla.transfersrealizationservice.service
  profiles:
    active: production
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${spring.application.name}
      properties:
        spring.json.trusted.packages: "com.kodilla.commons"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone=http://localhost:8761/eureka/:
server:
  port: 9991